"""
Visualization utilities for SSOD
"""

import cv2
import numpy as np
from pathlib import Path
from typing import List, Dict, Optional, Tuple
import matplotlib.pyplot as plt


def visualize_predictions(image: np.ndarray,
                         boxes: List,
                         classes: List,
                         confidences: List,
                         class_names: Optional[Dict[int, str]] = None,
                         color: Tuple[int, int, int] = (0, 255, 0),
                         thickness: int = 2) -> np.ndarray:
    """
    Draw bounding boxes on image.
    
    Args:
        image: Input image (BGR)
        boxes: List of boxes in YOLO format [class, x_center, y_center, w, h] normalized
        classes: List of class ids
        confidences: List of confidence scores
        class_names: Optional dict mapping class id to name
        color: Box color (BGR)
        thickness: Line thickness
        
    Returns:
        Image with drawn boxes
    """
    img = image.copy()
    h, w = img.shape[:2]
    
    for box, cls, conf in zip(boxes, classes, confidences):
        if len(box) == 5:
            _, x_c, y_c, bw, bh = box
        else:
            x_c, y_c, bw, bh = box
            
        # Convert to pixel coordinates
        x1 = int((x_c - bw / 2) * w)
        y1 = int((y_c - bh / 2) * h)
        x2 = int((x_c + bw / 2) * w)
        y2 = int((y_c + bh / 2) * h)
        
        # Draw box
        cv2.rectangle(img, (x1, y1), (x2, y2), color, thickness)
        
        # Draw label
        label = class_names.get(cls, f"cls_{cls}") if class_names else f"cls_{cls}"
        label = f"{label}: {conf:.2f}"
        
        (label_w, label_h), baseline = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)
        cv2.rectangle(img, (x1, y1 - label_h - 5), (x1 + label_w, y1), color, -1)
        cv2.putText(img, label, (x1, y1 - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1)
    
    return img


def visualize_comparison(fake_iron: np.ndarray,
                        real_iron: np.ndarray,
                        save_path: Optional[str] = None) -> plt.Figure:
    """
    Side-by-side comparison of Fake IronRed and Real IronRed.
    
    Args:
        fake_iron: Fake IronRed image (generated from colorization)
        real_iron: Real IronRed image
        save_path: Optional path to save the figure
        
    Returns:
        Matplotlib figure
    """
    fig, axes = plt.subplots(1, 2, figsize=(12, 6))
    
    # Convert BGR to RGB for matplotlib
    fake_rgb = cv2.cvtColor(fake_iron, cv2.COLOR_BGR2RGB)
    real_rgb = cv2.cvtColor(real_iron, cv2.COLOR_BGR2RGB)
    
    axes[0].imshow(fake_rgb)
    axes[0].set_title('Fake IronRed (Generated)')
    axes[0].axis('off')
    
    axes[1].imshow(real_rgb)
    axes[1].set_title('Real IronRed')
    axes[1].axis('off')
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"Comparison saved to {save_path}")
    
    plt.close()
    return fig


def visualize_pseudo_labels(image_path: str,
                           pseudo_labels: Dict,
                           save_path: Optional[str] = None) -> np.ndarray:
    """
    Visualize pseudo-labels generated by Teacher.
    
    Args:
        image_path: Path to image
        pseudo_labels: Dict with 'boxes_yolo', 'classes', 'confidences'
        save_path: Optional path to save result
        
    Returns:
        Image with pseudo-labels drawn
    """
    image = cv2.imread(image_path)
    if image is None:
        raise ValueError(f"Could not read image: {image_path}")
    
    result = visualize_predictions(
        image,
        pseudo_labels.get('boxes_yolo', []),
        pseudo_labels.get('classes', []),
        pseudo_labels.get('confidences', []),
        color=(255, 165, 0)  # Orange for pseudo-labels
    )
    
    if save_path:
        cv2.imwrite(save_path, result)
        
    return result


def create_training_visualization(epoch: int,
                                 loss_sup: float,
                                 loss_unsup: float,
                                 pseudo_ratio: float,
                                 threshold: float,
                                 save_dir: str):
    """Create visualization of training progress."""
    fig, axes = plt.subplots(2, 2, figsize=(10, 8))
    fig.suptitle(f'Training Progress - Epoch {epoch}')
    
    # Placeholder - will be filled with actual data during training
    axes[0, 0].set_title('Supervised Loss')
    axes[0, 1].set_title('Unsupervised Loss')
    axes[1, 0].set_title('Pseudo-label Ratio')
    axes[1, 1].set_title('Confidence Threshold')
    
    plt.tight_layout()
    
    save_path = Path(save_dir) / f"training_epoch{epoch}.png"
    plt.savefig(save_path, dpi=100)
    plt.close()
